services:
  cuda-dev:
    environment:
      DOCKER_HOST: unix:///var/run/docker.sock
    group_add:
      - "${DOCKER_SOCKET_GID}"
    volumes:
      - ${DOCKER_SOCKET_PATH:-/var/run/docker.sock}:/var/run/docker.sock
